### ISSUE TITLE
プログラムのディレクトリ名について

### ISSUE THREAD

**Issue by utgwkk** [ksuenaga/IoPLMaterials#13]
「プログラミング言語処理系」教科書16ページ注釈3の

>プログラムはこのリポジトリのminiMLInterp ディレクトリに格納されている．

は，正しくは

>プログラムはこのリポジトリのsrc ディレクトリに格納されている．

ではないでしょうか．

**Comment by ksuenaga** [comment]
たしかにそうです．直します．
