### ISSUE TITLE
予習クイズの解答について

### ISSUE THREAD

**Issue by AkitoSeki** [ksuenaga/IoPLMaterials#20]
中間試験の勉強のために予習クイズの解答をいただきたいのですが、可能でしょうか？

**Comment by ksuenaga** [comment]
すみません，講義でだいぶ手厚くやりましたし，一回目はほとんど OCaml インタプリタにプログラムを投げて応答を見る程度の問題で，二回目も講義資料を見ればすぐに分かるようになっているので，改めて解答を作ることは考えていません．
