### ISSUE TITLE
ex. code on textbook might be missing

### ISSUE THREAD

**Issue by katshun0307** [ksuenaga/IoPLMaterials#24]
*** censored ***

**Comment by katshun0307** [comment]
adding 
```
FUNExpr : (* function *)
    FUN x=ID RARROW e=Expr { FunExp (x, e) }
```
made functions work.

**Comment by kanra824** [comment]
I think it is also necessary to add a representation of ProcV to string_of_exval in eval.ml. (If you do not add it, an error occurs when you enter "fun x -> x + 1 ;;")

**Comment by kanra824** [comment]
```ocaml
# fun x -> x+1;;
val - = Fatal error: exception Match_failure("eval.ml", 14, 26)
```

**Comment by kanra824** [comment]
Sorry, have not implemented eval.ml yet? . If you implement eval.ml as it is in the textbook, the above problem will occur.

**Comment by ksuenaga** [comment]
@kanra824 @katshun0307 
Actually, filling this detail by yourself is intended to be a part of this exercise.
Do you mind if I remove the code you wrote on this issue so that the other students can learn by themselves?
Thanks!

**Comment by ksuenaga** [comment]
Thanks!
