### ISSUE TITLE
.gitignore should be updated

### ISSUE THREAD

**Issue by KMConner** [ksuenaga/IoPLMaterials#25]
The directory `src` was renamed for `interpreter` in commit d2751155badb0f72bba124b3d0d4b6b3c5d5cc6b.
However, directory name in .gitignore is still `src`.
So, these `src` should be changed to `interpreter`.

**Comment by ksuenaga** [comment]
Thanks!  I'll fix it soon.

**Comment by ksuenaga** [comment]
Done.
