### ISSUE TITLE
Excercise 1.0.2 (3) の型に違和感

### ISSUE THREAD

**Issue by nekketsuuu** [ksuenaga/IoPLMaterials#4]
[IoPLTextbook.pdf](https://github.com/ksuenaga/IoPLMaterials/blob/master/textbook/IoPLTextbook.pdf)の5ページにあるExercise 1.0.2 (3)にある`mapTree`の型ですが、`bt -> int -> int -> bt`よりも`bt -> (int -> int) -> bt`の方が正確ではないでしょうか。また、`List.map : ('a -> 'b) -> 'a list -> 'b list`のように`(int -> int) -> bt -> bt`型にしていないのには何か理由がございますか……？

**Comment by ksuenaga** [comment]
カッコが抜けてました．すみません．引数の順序については特に理由がないです．（が，提案してもらったやつに変えます．）
