### ISSUE TITLE
文法的に正しいC言語のプログラムの例が抜けている

### ISSUE THREAD

**Issue by nekketsuuu** [ksuenaga/IoPLMaterials#7]
[IoPLTextbook.pdf](https://github.com/ksuenaga/IoPLMaterials/blob/master/textbook/IoPLTextbook.pdf)のページ8にて「例えば，〜は文法的に正しいC言語のプログラムであるが，」という部分がありますが、波線部分に挿入されていたであろうプログラムが抜け落ちているのではないかと思います。

**Comment by ksuenaga** [comment]
これで多分治っていると思います．もしまだ見えないようでしたら reopen お願いします．
